name: Typedoc CI

on: [push]

jobs:
  tests:
    name: TypeDoc integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        typedoc-version:
          - latest
          - '~0.16.0'
          - '~0.15.0'
          - '~0.14.0'
          - '~0.13.0'
          - '~0.12.0'
          - '~0.11.0'
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-optional
        env:
          CI: true
      - name: Build
        run: yarn build
        env:
          CI: true
      - name: Link
        run: yarn link
      - name: TypeDoc integration test
        run: |
          cd ~ && mkdir -p example/src && cd example
          yarn init -y
          yarn add -D typedoc@${{ matrix.typedoc-version }}
          echo '{"compilerOptions": {"target": "es5","module": "commonjs","lib": ["es2015"],"strict": true,"esModuleInterop": true,"forceConsistentCasingInFileNames": true}}' >> tsconfig.json
          echo 'export class HelloWorld {}' >> src/hello-world.ts
          yarn link typedoc-plugin-nomnoml
          yarn run typedoc --mode file \
            --plugin typedoc-plugin-nomnoml \
            --out docs \
            src
